### PR TITLE
Add formal names, data migration

### PR DESCRIPTION
**Pull request by afrasier**
@mjoyce91 you'll want to look at "formal_description" in most cases now

### CODE REVIEW

**Comment by burgwyn** [comment]
@afrasier - do we include Language in the sync cron jobs?

**Comment by afrasier** [comment]
Yes.

**Comment by burgwyn** [comment]
Would it make sense to exclude them?

**Comment by afrasier** [comment]
No. We need to sync as it only ever provides languages for which a position is available. Why would we want to exclude them?

**Comment by burgwyn** [comment]
That makes sense.  I was just worried about the sync disrupting the `formal_date`s

**Pull request merged**
